# Generated by Django 4.2.13 on 2025-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCostabella', '0002_empleados_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosventa',
            name='descuento',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
