# Generated by Django 4.2.13 on 2025-02-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCostabella', '0003_productosventa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosventa',
            name='descuento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
